# Generated by Django 3.1.14 on 2023-04-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='video_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
